### ISSUE TITLE
可用ip太少

### ISSUE THREAD

**Issue by opengit** [imWildCat/scylla#38]
您好~ 可用ip太少，是不是采集的免费代理网站都挂了？另外，作者有没有计划加入更多的国内ip，减少使用时的延迟~~谢谢
![image](https://user-images.githubusercontent.com/12468408/41403431-71abe3c6-6ff7-11e8-8c5e-9fc5e599bc52.png)

**Comment by imWildCat** [comment]
I suggest you reorganise you language expression formally, writing in English as well.

If you meet this requirement, feel free to reopen this issue.

It is necessary to express your idea in English formally because people from a variety of countries may help you rather than those from your country only.
